/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as CotizacionesRouteImport } from './routes/cotizaciones'
import { Route as CotizarRouteImport } from './routes/cotizar'
import { Route as CuentaRouteImport } from './routes/cuenta'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProteccionRouteImport } from './routes/proteccion'
import { Route as ProveedoresRouteImport } from './routes/proveedores'
import { Route as RestablecerRouteImport } from './routes/restablecer'
import { Route as SolicitudesRouteImport } from './routes/solicitudes'
import { Route as InstitucionalIndexRouteImport } from './routes/institucional/index'
import { Route as InstitucionalSlugRouteImport } from './routes/institucional/$slug'
import { Route as NegocioBusinessIdRouteImport } from './routes/negocio/$businessId'
import { Route as PanelIndexRouteImport } from './routes/panel/index'
import { Route as PedidosIndexRouteImport } from './routes/pedidos/index'
import { Route as PedidosOrderIdRouteImport } from './routes/pedidos/$orderId'
import { Route as ProductoProductIdRouteImport } from './routes/producto/$productId'
import { Route as SolicitudRequestIdRouteImport } from './routes/solicitud/$requestId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiMediaSplatRouteImport } from './routes/api/media/$'
import { Route as PanelProductosIndexRouteImport } from './routes/panel/productos/index'
import { Route as PanelProductosListingIdRouteImport } from './routes/panel/productos/$listingId'
import { Route as ApiPaymentsMercadopagoIndexRouteImport } from './routes/api/payments/mercadopago/index'
import { Route as ApiPaymentsMercadopagoCallbackRouteImport } from './routes/api/payments/mercadopago/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const CotizacionesRoute = CotizacionesRouteImport.update({
  id: '/cotizaciones',
  path: '/cotizaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const CotizarRoute = CotizarRouteImport.update({
  id: '/cotizar',
  path: '/cotizar',
  getParentRoute: () => rootRouteImport,
} as any)
const CuentaRoute = CuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProteccionRoute = ProteccionRouteImport.update({
  id: '/proteccion',
  path: '/proteccion',
  getParentRoute: () => rootRouteImport,
} as any)
const ProveedoresRoute = ProveedoresRouteImport.update({
  id: '/proveedores',
  path: '/proveedores',
  getParentRoute: () => rootRouteImport,
} as any)
const RestablecerRoute = RestablecerRouteImport.update({
  id: '/restablecer',
  path: '/restablecer',
  getParentRoute: () => rootRouteImport,
} as any)
const SolicitudesRoute = SolicitudesRouteImport.update({
  id: '/solicitudes',
  path: '/solicitudes',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitucionalIndexRoute = InstitucionalIndexRouteImport.update({
  id: '/institucional/',
  path: '/institucional/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitucionalSlugRoute = InstitucionalSlugRouteImport.update({
  id: '/institucional/$slug',
  path: '/institucional/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NegocioBusinessIdRoute = NegocioBusinessIdRouteImport.update({
  id: '/negocio/$businessId',
  path: '/negocio/$businessId',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelIndexRoute = PanelIndexRouteImport.update({
  id: '/panel/',
  path: '/panel/',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosIndexRoute = PedidosIndexRouteImport.update({
  id: '/pedidos/',
  path: '/pedidos/',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosOrderIdRoute = PedidosOrderIdRouteImport.update({
  id: '/pedidos/$orderId',
  path: '/pedidos/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductoProductIdRoute = ProductoProductIdRouteImport.update({
  id: '/producto/$productId',
  path: '/producto/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const SolicitudRequestIdRoute = SolicitudRequestIdRouteImport.update({
  id: '/solicitud/$requestId',
  path: '/solicitud/$requestId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaSplatRoute = ApiMediaSplatRouteImport.update({
  id: '/api/media/$',
  path: '/api/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelProductosIndexRoute = PanelProductosIndexRouteImport.update({
  id: '/panel/productos/',
  path: '/panel/productos/',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelProductosListingIdRoute = PanelProductosListingIdRouteImport.update({
  id: '/panel/productos/$listingId',
  path: '/panel/productos/$listingId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsMercadopagoIndexRoute =
  ApiPaymentsMercadopagoIndexRouteImport.update({
    id: '/api/payments/mercadopago/',
    path: '/api/payments/mercadopago/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPaymentsMercadopagoCallbackRoute =
  ApiPaymentsMercadopagoCallbackRouteImport.update({
    id: '/api/payments/mercadopago/callback',
    path: '/api/payments/mercadopago/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/categorias': typeof CategoriasRoute
  '/cotizaciones': typeof CotizacionesRoute
  '/cotizar': typeof CotizarRoute
  '/cuenta': typeof CuentaRoute
  '/login': typeof LoginRoute
  '/proteccion': typeof ProteccionRoute
  '/proveedores': typeof ProveedoresRoute
  '/restablecer': typeof RestablecerRoute
  '/solicitudes': typeof SolicitudesRoute
  '/institucional/$slug': typeof InstitucionalSlugRoute
  '/negocio/$businessId': typeof NegocioBusinessIdRoute
  '/pedidos/$orderId': typeof PedidosOrderIdRoute
  '/producto/$productId': typeof ProductoProductIdRoute
  '/solicitud/$requestId': typeof SolicitudRequestIdRoute
  '/institucional/': typeof InstitucionalIndexRoute
  '/panel/': typeof PanelIndexRoute
  '/pedidos/': typeof PedidosIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$': typeof ApiMediaSplatRoute
  '/panel/productos/$listingId': typeof PanelProductosListingIdRoute
  '/panel/productos/': typeof PanelProductosIndexRoute
  '/api/payments/mercadopago/callback': typeof ApiPaymentsMercadopagoCallbackRoute
  '/api/payments/mercadopago/': typeof ApiPaymentsMercadopagoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/categorias': typeof CategoriasRoute
  '/cotizaciones': typeof CotizacionesRoute
  '/cotizar': typeof CotizarRoute
  '/cuenta': typeof CuentaRoute
  '/login': typeof LoginRoute
  '/proteccion': typeof ProteccionRoute
  '/proveedores': typeof ProveedoresRoute
  '/restablecer': typeof RestablecerRoute
  '/solicitudes': typeof SolicitudesRoute
  '/institucional/$slug': typeof InstitucionalSlugRoute
  '/negocio/$businessId': typeof NegocioBusinessIdRoute
  '/pedidos/$orderId': typeof PedidosOrderIdRoute
  '/producto/$productId': typeof ProductoProductIdRoute
  '/solicitud/$requestId': typeof SolicitudRequestIdRoute
  '/institucional': typeof InstitucionalIndexRoute
  '/panel': typeof PanelIndexRoute
  '/pedidos': typeof PedidosIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$': typeof ApiMediaSplatRoute
  '/panel/productos/$listingId': typeof PanelProductosListingIdRoute
  '/panel/productos': typeof PanelProductosIndexRoute
  '/api/payments/mercadopago/callback': typeof ApiPaymentsMercadopagoCallbackRoute
  '/api/payments/mercadopago': typeof ApiPaymentsMercadopagoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/categorias': typeof CategoriasRoute
  '/cotizaciones': typeof CotizacionesRoute
  '/cotizar': typeof CotizarRoute
  '/cuenta': typeof CuentaRoute
  '/login': typeof LoginRoute
  '/proteccion': typeof ProteccionRoute
  '/proveedores': typeof ProveedoresRoute
  '/restablecer': typeof RestablecerRoute
  '/solicitudes': typeof SolicitudesRoute
  '/institucional/$slug': typeof InstitucionalSlugRoute
  '/negocio/$businessId': typeof NegocioBusinessIdRoute
  '/pedidos/$orderId': typeof PedidosOrderIdRoute
  '/producto/$productId': typeof ProductoProductIdRoute
  '/solicitud/$requestId': typeof SolicitudRequestIdRoute
  '/institucional/': typeof InstitucionalIndexRoute
  '/panel/': typeof PanelIndexRoute
  '/pedidos/': typeof PedidosIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$': typeof ApiMediaSplatRoute
  '/panel/productos/$listingId': typeof PanelProductosListingIdRoute
  '/panel/productos/': typeof PanelProductosIndexRoute
  '/api/payments/mercadopago/callback': typeof ApiPaymentsMercadopagoCallbackRoute
  '/api/payments/mercadopago/': typeof ApiPaymentsMercadopagoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/categorias'
    | '/cotizaciones'
    | '/cotizar'
    | '/cuenta'
    | '/login'
    | '/proteccion'
    | '/proveedores'
    | '/restablecer'
    | '/solicitudes'
    | '/institucional/$slug'
    | '/negocio/$businessId'
    | '/pedidos/$orderId'
    | '/producto/$productId'
    | '/solicitud/$requestId'
    | '/institucional/'
    | '/panel/'
    | '/pedidos/'
    | '/api/auth/$'
    | '/api/media/$'
    | '/panel/productos/$listingId'
    | '/panel/productos/'
    | '/api/payments/mercadopago/callback'
    | '/api/payments/mercadopago/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/categorias'
    | '/cotizaciones'
    | '/cotizar'
    | '/cuenta'
    | '/login'
    | '/proteccion'
    | '/proveedores'
    | '/restablecer'
    | '/solicitudes'
    | '/institucional/$slug'
    | '/negocio/$businessId'
    | '/pedidos/$orderId'
    | '/producto/$productId'
    | '/solicitud/$requestId'
    | '/institucional'
    | '/panel'
    | '/pedidos'
    | '/api/auth/$'
    | '/api/media/$'
    | '/panel/productos/$listingId'
    | '/panel/productos'
    | '/api/payments/mercadopago/callback'
    | '/api/payments/mercadopago'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/categorias'
    | '/cotizaciones'
    | '/cotizar'
    | '/cuenta'
    | '/login'
    | '/proteccion'
    | '/proveedores'
    | '/restablecer'
    | '/solicitudes'
    | '/institucional/$slug'
    | '/negocio/$businessId'
    | '/pedidos/$orderId'
    | '/producto/$productId'
    | '/solicitud/$requestId'
    | '/institucional/'
    | '/panel/'
    | '/pedidos/'
    | '/api/auth/$'
    | '/api/media/$'
    | '/panel/productos/$listingId'
    | '/panel/productos/'
    | '/api/payments/mercadopago/callback'
    | '/api/payments/mercadopago/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CategoriasRoute: typeof CategoriasRoute
  CotizacionesRoute: typeof CotizacionesRoute
  CotizarRoute: typeof CotizarRoute
  CuentaRoute: typeof CuentaRoute
  LoginRoute: typeof LoginRoute
  ProteccionRoute: typeof ProteccionRoute
  ProveedoresRoute: typeof ProveedoresRoute
  RestablecerRoute: typeof RestablecerRoute
  SolicitudesRoute: typeof SolicitudesRoute
  InstitucionalSlugRoute: typeof InstitucionalSlugRoute
  NegocioBusinessIdRoute: typeof NegocioBusinessIdRoute
  PedidosOrderIdRoute: typeof PedidosOrderIdRoute
  ProductoProductIdRoute: typeof ProductoProductIdRoute
  SolicitudRequestIdRoute: typeof SolicitudRequestIdRoute
  InstitucionalIndexRoute: typeof InstitucionalIndexRoute
  PanelIndexRoute: typeof PanelIndexRoute
  PedidosIndexRoute: typeof PedidosIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMediaSplatRoute: typeof ApiMediaSplatRoute
  PanelProductosListingIdRoute: typeof PanelProductosListingIdRoute
  PanelProductosIndexRoute: typeof PanelProductosIndexRoute
  ApiPaymentsMercadopagoCallbackRoute: typeof ApiPaymentsMercadopagoCallbackRoute
  ApiPaymentsMercadopagoIndexRoute: typeof ApiPaymentsMercadopagoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotizaciones': {
      id: '/cotizaciones'
      path: '/cotizaciones'
      fullPath: '/cotizaciones'
      preLoaderRoute: typeof CotizacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotizar': {
      id: '/cotizar'
      path: '/cotizar'
      fullPath: '/cotizar'
      preLoaderRoute: typeof CotizarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuenta': {
      id: '/cuenta'
      path: '/cuenta'
      fullPath: '/cuenta'
      preLoaderRoute: typeof CuentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proteccion': {
      id: '/proteccion'
      path: '/proteccion'
      fullPath: '/proteccion'
      preLoaderRoute: typeof ProteccionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proveedores': {
      id: '/proveedores'
      path: '/proveedores'
      fullPath: '/proveedores'
      preLoaderRoute: typeof ProveedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restablecer': {
      id: '/restablecer'
      path: '/restablecer'
      fullPath: '/restablecer'
      preLoaderRoute: typeof RestablecerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solicitudes': {
      id: '/solicitudes'
      path: '/solicitudes'
      fullPath: '/solicitudes'
      preLoaderRoute: typeof SolicitudesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institucional/': {
      id: '/institucional/'
      path: '/institucional'
      fullPath: '/institucional/'
      preLoaderRoute: typeof InstitucionalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institucional/$slug': {
      id: '/institucional/$slug'
      path: '/institucional/$slug'
      fullPath: '/institucional/$slug'
      preLoaderRoute: typeof InstitucionalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/negocio/$businessId': {
      id: '/negocio/$businessId'
      path: '/negocio/$businessId'
      fullPath: '/negocio/$businessId'
      preLoaderRoute: typeof NegocioBusinessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/': {
      id: '/panel/'
      path: '/panel'
      fullPath: '/panel/'
      preLoaderRoute: typeof PanelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos/': {
      id: '/pedidos/'
      path: '/pedidos'
      fullPath: '/pedidos/'
      preLoaderRoute: typeof PedidosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos/$orderId': {
      id: '/pedidos/$orderId'
      path: '/pedidos/$orderId'
      fullPath: '/pedidos/$orderId'
      preLoaderRoute: typeof PedidosOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producto/$productId': {
      id: '/producto/$productId'
      path: '/producto/$productId'
      fullPath: '/producto/$productId'
      preLoaderRoute: typeof ProductoProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solicitud/$requestId': {
      id: '/solicitud/$requestId'
      path: '/solicitud/$requestId'
      fullPath: '/solicitud/$requestId'
      preLoaderRoute: typeof SolicitudRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$': {
      id: '/api/media/$'
      path: '/api/media/$'
      fullPath: '/api/media/$'
      preLoaderRoute: typeof ApiMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/productos/': {
      id: '/panel/productos/'
      path: '/panel/productos'
      fullPath: '/panel/productos/'
      preLoaderRoute: typeof PanelProductosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/productos/$listingId': {
      id: '/panel/productos/$listingId'
      path: '/panel/productos/$listingId'
      fullPath: '/panel/productos/$listingId'
      preLoaderRoute: typeof PanelProductosListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/mercadopago/': {
      id: '/api/payments/mercadopago/'
      path: '/api/payments/mercadopago'
      fullPath: '/api/payments/mercadopago/'
      preLoaderRoute: typeof ApiPaymentsMercadopagoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/mercadopago/callback': {
      id: '/api/payments/mercadopago/callback'
      path: '/api/payments/mercadopago/callback'
      fullPath: '/api/payments/mercadopago/callback'
      preLoaderRoute: typeof ApiPaymentsMercadopagoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CategoriasRoute: CategoriasRoute,
  CotizacionesRoute: CotizacionesRoute,
  CotizarRoute: CotizarRoute,
  CuentaRoute: CuentaRoute,
  LoginRoute: LoginRoute,
  ProteccionRoute: ProteccionRoute,
  ProveedoresRoute: ProveedoresRoute,
  RestablecerRoute: RestablecerRoute,
  SolicitudesRoute: SolicitudesRoute,
  InstitucionalSlugRoute: InstitucionalSlugRoute,
  NegocioBusinessIdRoute: NegocioBusinessIdRoute,
  PedidosOrderIdRoute: PedidosOrderIdRoute,
  ProductoProductIdRoute: ProductoProductIdRoute,
  SolicitudRequestIdRoute: SolicitudRequestIdRoute,
  InstitucionalIndexRoute: InstitucionalIndexRoute,
  PanelIndexRoute: PanelIndexRoute,
  PedidosIndexRoute: PedidosIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMediaSplatRoute: ApiMediaSplatRoute,
  PanelProductosListingIdRoute: PanelProductosListingIdRoute,
  PanelProductosIndexRoute: PanelProductosIndexRoute,
  ApiPaymentsMercadopagoCallbackRoute: ApiPaymentsMercadopagoCallbackRoute,
  ApiPaymentsMercadopagoIndexRoute: ApiPaymentsMercadopagoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
