-- Categorías de vendedor. No mueve las categorías de construcción ya usadas por publicaciones.
-- No inserta productos, proveedores ni precios.

alter table categories add column if not exists icon text;
alter table categories add column if not exists description text not null default '';
alter table categories add column if not exists is_featured boolean not null default false;
alter table categories add column if not exists sort_order integer not null default 1000;
alter table categories add column if not exists synonyms text not null default '';

create table if not exists business_categories (
  business_id text not null references businesses (id) on delete cascade,
  category_id text not null references categories (id),
  created_at timestamptz not null default now(),
  primary key (business_id, category_id)
);

insert into platform_settings (key, value)
values ('seller_category_limit', '10'::jsonb)
on conflict (key) do nothing;

insert into categories (id, parent_id, slug, name, vertical, icon, description, is_featured, sort_order, synonyms)
values
  ('tecnologia', null, 'tecnologia', 'Tecnología', 'general', 'technology', 'Productos relacionados con tecnología y electrónica.', true, 1, 'electronica tecnologia'),
  ('moda', null, 'moda', 'Moda e Indumentaria', 'general', 'fashion', 'Ropa, calzado y accesorios.', true, 2, 'ropa moda indumentaria'),
  ('hogar', null, 'hogar', 'Hogar y Muebles', 'general', 'home', 'Hogar, decoración y jardín.', true, 3, 'hogar muebles'),
  ('alimentos', null, 'alimentos', 'Alimentos y Bebidas', 'general', 'food', 'Productos destinados al consumo.', true, 4, 'comida bebida'),
  ('deportes', null, 'deportes', 'Deportes y Fitness', 'general', 'sports', 'Deporte y actividad física.', true, 5, 'deporte fitness'),
  ('vehiculos', null, 'vehiculos', 'Vehículos y Accesorios', 'general', 'vehicles', 'Vehículos, repuestos y accesorios.', true, 6, 'auto moto vehiculo'),
  ('belleza', null, 'belleza', 'Belleza y Cuidado Personal', 'general', 'beauty', 'Belleza, cosmética e higiene.', true, 7, 'belleza cosmetica'),
  ('herramientas-construccion', null, 'herramientas-construccion', 'Herramientas y Construcción', 'general', 'tools', 'Construcción, reparación y mantenimiento.', true, 8, 'construccion herramienta ferreteria'),
  ('juguetes-bebes', null, 'juguetes-bebes', 'Juguetes, Bebés y Niños', 'general', 'kids', 'Bebés, niños y entretenimiento infantil.', true, 9, 'juguete bebe nino'),
  ('mascotas', null, 'mascotas', 'Mascotas', 'general', 'pets', 'Productos para animales.', true, 10, 'mascota animal'),
  ('inmuebles', null, 'inmuebles', 'Inmuebles', 'general', 'property', 'Inmuebles y espacios.', false, 20, 'inmueble propiedad'),
  ('industrias-oficinas', null, 'industrias-oficinas', 'Industrias y Oficinas', 'general', 'industry', 'Equipamiento industrial, comercial y de oficina.', false, 21, 'industria oficina'),
  ('agro', null, 'agro', 'Agro', 'general', 'agro', 'Campo, cultivos y ganadería.', false, 22, 'agro campo'),
  ('salud-medica', null, 'salud-medica', 'Salud y Equipamiento Médico', 'general', 'health', 'Salud y equipamiento médico.', false, 23, 'salud medico'),
  ('instrumentos-musicales', null, 'instrumentos-musicales', 'Instrumentos Musicales', 'general', 'music', 'Instrumentos y audio musical.', false, 24, 'musica instrumento'),
  ('libros-arte', null, 'libros-arte', 'Libros, Librería y Arte', 'general', 'books', 'Libros, librería y arte.', false, 25, 'libro arte libreria'),
  ('joyas-relojes', null, 'joyas-relojes', 'Joyas y Relojes', 'general', 'jewelry', 'Joyas, relojes y bijouterie.', false, 26, 'joya reloj'),
  ('antiguedades', null, 'antiguedades', 'Antigüedades y Colecciones', 'general', 'antiques', 'Antigüedades y objetos de colección.', false, 27, 'antiguedad coleccion'),
  ('fiestas-eventos', null, 'fiestas-eventos', 'Fiestas y Eventos', 'general', 'parties', 'Fiestas, cotillón y eventos.', false, 28, 'fiesta evento'),
  ('servicios', null, 'servicios', 'Servicios', 'general', 'services', 'Servicios. No reemplaza la categoría de un producto.', false, 29, 'servicio'),
  ('celulares', 'tecnologia', 'celulares', 'Celulares', 'general', null, '', false, 100, 'smartphone smartphones telefono'),
  ('computadoras', 'tecnologia', 'computadoras', 'Computadoras', 'general', null, '', false, 100, 'computadora pc'),
  ('notebooks', 'tecnologia', 'notebooks', 'Notebooks', 'general', null, '', false, 100, 'notebook laptop'),
  ('pc-gaming', 'tecnologia', 'pc-gaming', 'PC Gaming', 'general', null, '', false, 100, 'gaming pc'),
  ('componentes-pc', 'tecnologia', 'componentes-pc', 'Componentes de PC', 'general', null, '', false, 100, 'componentes'),
  ('monitores', 'tecnologia', 'monitores', 'Monitores', 'general', null, '', false, 100, 'monitor'),
  ('tablets', 'tecnologia', 'tablets', 'Tablets', 'general', null, '', false, 100, 'tablet'),
  ('impresoras', 'tecnologia', 'impresoras', 'Impresoras', 'general', null, '', false, 100, 'impresora'),
  ('televisores', 'tecnologia', 'televisores', 'Televisores', 'general', null, '', false, 100, 'televisor tv smart tv'),
  ('consolas', 'tecnologia', 'consolas', 'Consolas', 'general', null, '', false, 100, 'consola playstation xbox'),
  ('videojuegos', 'tecnologia', 'videojuegos', 'Videojuegos', 'general', null, '', false, 100, 'videojuego juego'),
  ('drones', 'tecnologia', 'drones', 'Drones', 'general', null, '', false, 100, 'drone'),
  ('camaras', 'tecnologia', 'camaras', 'Cámaras', 'general', null, '', false, 100, 'camara'),
  ('audio', 'tecnologia', 'audio', 'Audio', 'general', null, '', false, 100, 'auriculares parlante'),
  ('accesorios-tecnologicos', 'tecnologia', 'accesorios-tecnologicos', 'Accesorios tecnológicos', 'general', null, '', false, 100, 'accesorio tecnologico'),
  ('redes', 'tecnologia', 'redes', 'Redes', 'general', null, '', false, 100, 'router wifi'),
  ('electronica', 'tecnologia', 'electronica', 'Electrónica', 'general', null, '', false, 100, 'electronica'),
  ('domotica', 'tecnologia', 'domotica', 'Domótica', 'general', null, '', false, 100, 'domotica'),
  ('remeras', 'moda', 'remeras', 'Remeras', 'general', null, '', false, 100, 'remera'),
  ('musculosas', 'moda', 'musculosas', 'Musculosas', 'general', null, '', false, 100, 'musculosa'),
  ('camisas', 'moda', 'camisas', 'Camisas', 'general', null, '', false, 100, 'camisa'),
  ('chombas', 'moda', 'chombas', 'Chombas', 'general', null, '', false, 100, 'chomba'),
  ('pantalones', 'moda', 'pantalones', 'Pantalones', 'general', null, '', false, 100, 'pantalon'),
  ('bermudas', 'moda', 'bermudas', 'Bermudas', 'general', null, '', false, 100, 'bermuda'),
  ('shorts', 'moda', 'shorts', 'Shorts', 'general', null, '', false, 100, 'short'),
  ('calzas', 'moda', 'calzas', 'Calzas', 'general', null, '', false, 100, 'calza'),
  ('vestidos', 'moda', 'vestidos', 'Vestidos', 'general', null, '', false, 100, 'vestido'),
  ('polleras', 'moda', 'polleras', 'Polleras', 'general', null, '', false, 100, 'pollera'),
  ('camperas', 'moda', 'camperas', 'Camperas', 'general', null, '', false, 100, 'campera'),
  ('buzos', 'moda', 'buzos', 'Buzos', 'general', null, '', false, 100, 'buzo'),
  ('abrigos', 'moda', 'abrigos', 'Abrigos', 'general', null, '', false, 100, 'abrigo'),
  ('ropa-deportiva', 'moda', 'ropa-deportiva', 'Ropa deportiva', 'general', null, '', false, 100, 'deportiva'),
  ('ropa-interior', 'moda', 'ropa-interior', 'Ropa interior', 'general', null, '', false, 100, 'interior'),
  ('lenceria', 'moda', 'lenceria', 'Lencería', 'general', null, '', false, 100, 'lenceria'),
  ('ropa-dormir', 'moda', 'ropa-dormir', 'Ropa de dormir', 'general', null, '', false, 100, 'pijama'),
  ('trajes-bano', 'moda', 'trajes-bano', 'Trajes de baño', 'general', null, '', false, 100, 'malla bikini'),
  ('zapatillas', 'moda', 'zapatillas', 'Zapatillas', 'general', null, '', false, 100, 'zapatilla'),
  ('zapatos', 'moda', 'zapatos', 'Zapatos', 'general', null, '', false, 100, 'zapato'),
  ('botas', 'moda', 'botas', 'Botas', 'general', null, '', false, 100, 'bota'),
  ('carteras', 'moda', 'carteras', 'Carteras', 'general', null, '', false, 100, 'cartera'),
  ('mochilas', 'moda', 'mochilas', 'Mochilas', 'general', null, '', false, 100, 'mochila'),
  ('bolsos', 'moda', 'bolsos', 'Bolsos', 'general', null, '', false, 100, 'bolso'),
  ('gorras', 'moda', 'gorras', 'Gorras', 'general', null, '', false, 100, 'gorra'),
  ('accesorios-moda', 'moda', 'accesorios-moda', 'Accesorios de moda', 'general', null, '', false, 100, 'accesorio'),
  ('ropa-infantil', 'moda', 'ropa-infantil', 'Ropa infantil', 'general', null, '', false, 100, 'infantil'),
  ('ropa-laboral', 'moda', 'ropa-laboral', 'Ropa laboral', 'general', null, '', false, 100, 'trabajo'),
  ('muebles', 'hogar', 'muebles', 'Muebles', 'general', null, '', false, 100, 'mueble'),
  ('mesas', 'hogar', 'mesas', 'Mesas', 'general', null, '', false, 100, 'mesa'),
  ('sillas', 'hogar', 'sillas', 'Sillas', 'general', null, '', false, 100, 'silla'),
  ('sillones', 'hogar', 'sillones', 'Sillones', 'general', null, '', false, 100, 'sillon'),
  ('camas', 'hogar', 'camas', 'Camas', 'general', null, '', false, 100, 'cama'),
  ('colchones', 'hogar', 'colchones', 'Colchones', 'general', null, '', false, 100, 'colchon'),
  ('placares', 'hogar', 'placares', 'Placares', 'general', null, '', false, 100, 'placard'),
  ('decoracion', 'hogar', 'decoracion', 'Decoración', 'general', null, '', false, 100, 'decoracion'),
  ('iluminacion', 'hogar', 'iluminacion', 'Iluminación', 'general', null, '', false, 100, 'lampara iluminacion'),
  ('bazar', 'hogar', 'bazar', 'Bazar', 'general', null, '', false, 100, 'bazar'),
  ('cocina', 'hogar', 'cocina', 'Cocina', 'general', null, '', false, 100, 'cocina'),
  ('bano-hogar', 'hogar', 'bano-hogar', 'Baño', 'general', null, '', false, 100, 'bano'),
  ('organizacion', 'hogar', 'organizacion', 'Organización', 'general', null, '', false, 100, 'organizacion'),
  ('almacenamiento', 'hogar', 'almacenamiento', 'Almacenamiento', 'general', null, '', false, 100, 'almacenamiento'),
  ('textiles-hogar', 'hogar', 'textiles-hogar', 'Textiles para el hogar', 'general', null, '', false, 100, 'textil sabanas'),
  ('jardin', 'hogar', 'jardin', 'Jardín', 'general', null, '', false, 100, 'jardin'),
  ('parrillas', 'hogar', 'parrillas', 'Parrillas', 'general', null, '', false, 100, 'parrilla asado'),
  ('exterior', 'hogar', 'exterior', 'Productos para exterior', 'general', null, '', false, 100, 'exterior'),
  ('seguridad-hogar', 'hogar', 'seguridad-hogar', 'Seguridad para el hogar', 'general', null, '', false, 100, 'alarma'),
  ('electrodomesticos', 'hogar', 'electrodomesticos', 'Electrodomésticos', 'general', null, '', false, 100, 'electrodomestico'),
  ('almacen', 'alimentos', 'almacen', 'Almacén', 'general', null, '', false, 100, 'almacen'),
  ('bebidas', 'alimentos', 'bebidas', 'Bebidas', 'general', null, '', false, 100, 'bebida'),
  ('snacks', 'alimentos', 'snacks', 'Snacks', 'general', null, '', false, 100, 'snack'),
  ('golosinas', 'alimentos', 'golosinas', 'Golosinas', 'general', null, '', false, 100, 'golosina'),
  ('yerba', 'alimentos', 'yerba', 'Yerba', 'general', null, '', false, 100, 'yerba mate'),
  ('cafe', 'alimentos', 'cafe', 'Café', 'general', null, '', false, 100, 'cafe'),
  ('te', 'alimentos', 'te', 'Té', 'general', null, '', false, 100, 'te'),
  ('alimentos-secos', 'alimentos', 'alimentos-secos', 'Alimentos secos', 'general', null, '', false, 100, 'seco'),
  ('alimentos-frescos', 'alimentos', 'alimentos-frescos', 'Alimentos frescos', 'general', null, '', false, 100, 'fresco'),
  ('congelados', 'alimentos', 'congelados', 'Congelados', 'general', null, '', false, 100, 'congelado'),
  ('comida-preparada', 'alimentos', 'comida-preparada', 'Comida preparada', 'general', null, '', false, 100, 'preparada'),
  ('gourmet', 'alimentos', 'gourmet', 'Productos gourmet', 'general', null, '', false, 100, 'gourmet'),
  ('productos-naturales', 'alimentos', 'productos-naturales', 'Productos naturales', 'general', null, '', false, 100, 'natural'),
  ('dietas', 'alimentos', 'dietas', 'Alimentos para dietas específicas', 'general', null, '', false, 100, 'celiaco vegano'),
  ('futbol', 'deportes', 'futbol', 'Fútbol', 'general', null, '', false, 100, 'futbol pelota'),
  ('basquet', 'deportes', 'basquet', 'Básquet', 'general', null, '', false, 100, 'basquetbol basket'),
  ('tenis', 'deportes', 'tenis', 'Tenis', 'general', null, '', false, 100, 'tenis'),
  ('padel', 'deportes', 'padel', 'Pádel', 'general', null, '', false, 100, 'padel'),
  ('voley', 'deportes', 'voley', 'Vóley', 'general', null, '', false, 100, 'voleibol'),
  ('rugby', 'deportes', 'rugby', 'Rugby', 'general', null, '', false, 100, 'rugby'),
  ('futbol-americano', 'deportes', 'futbol-americano', 'Fútbol americano', 'general', null, '', false, 100, 'americano'),
  ('beisbol', 'deportes', 'beisbol', 'Béisbol', 'general', null, '', false, 100, 'beisbol'),
  ('golf', 'deportes', 'golf', 'Golf', 'general', null, '', false, 100, 'golf'),
  ('boxeo', 'deportes', 'boxeo', 'Boxeo', 'general', null, '', false, 100, 'boxeo'),
  ('artes-marciales', 'deportes', 'artes-marciales', 'Artes marciales', 'general', null, '', false, 100, 'marcial'),
  ('running', 'deportes', 'running', 'Running', 'general', null, '', false, 100, 'running correr'),
  ('ciclismo', 'deportes', 'ciclismo', 'Ciclismo', 'general', null, '', false, 100, 'bicicleta ciclismo'),
  ('skate', 'deportes', 'skate', 'Skate', 'general', null, '', false, 100, 'skate skateboard'),
  ('camping', 'deportes', 'camping', 'Camping', 'general', null, '', false, 100, 'camping'),
  ('pesca', 'deportes', 'pesca', 'Pesca', 'general', null, '', false, 100, 'pesca'),
  ('trekking', 'deportes', 'trekking', 'Trekking', 'general', null, '', false, 100, 'trekking'),
  ('natacion', 'deportes', 'natacion', 'Natación', 'general', null, '', false, 100, 'natacion pileta'),
  ('fitness', 'deportes', 'fitness', 'Fitness', 'general', null, '', false, 100, 'fitness'),
  ('musculacion', 'deportes', 'musculacion', 'Musculación', 'general', null, '', false, 100, 'musculacion gym'),
  ('yoga', 'deportes', 'yoga', 'Yoga', 'general', null, '', false, 100, 'yoga'),
  ('pilates', 'deportes', 'pilates', 'Pilates', 'general', null, '', false, 100, 'pilates'),
  ('ropa-deportiva-fitness', 'deportes', 'ropa-deportiva-fitness', 'Ropa deportiva', 'general', null, '', false, 100, 'ropa deporte'),
  ('zapatillas-deportivas', 'deportes', 'zapatillas-deportivas', 'Zapatillas deportivas', 'general', null, '', false, 100, 'zapatilla deporte'),
  ('pelotas', 'deportes', 'pelotas', 'Pelotas', 'general', null, '', false, 100, 'pelota'),
  ('equipamiento-deportivo', 'deportes', 'equipamiento-deportivo', 'Equipamiento deportivo', 'general', null, '', false, 100, 'equipamiento'),
  ('accesorios-deportivos', 'deportes', 'accesorios-deportivos', 'Accesorios deportivos', 'general', null, '', false, 100, 'accesorio deporte'),
  ('suplementos', 'deportes', 'suplementos', 'Suplementos deportivos', 'general', null, '', false, 100, 'suplemento proteina'),
  ('autos', 'vehiculos', 'autos', 'Autos', 'general', null, '', false, 100, 'auto automovil'),
  ('camionetas', 'vehiculos', 'camionetas', 'Camionetas', 'general', null, '', false, 100, 'camioneta'),
  ('motos', 'vehiculos', 'motos', 'Motos', 'general', null, '', false, 100, 'moto'),
  ('camiones', 'vehiculos', 'camiones', 'Camiones', 'general', null, '', false, 100, 'camion'),
  ('nautica', 'vehiculos', 'nautica', 'Náutica', 'general', null, '', false, 100, 'nautica lancha'),
  ('vehiculos-coleccion', 'vehiculos', 'vehiculos-coleccion', 'Vehículos de colección', 'general', null, '', false, 100, 'coleccion'),
  ('repuestos', 'vehiculos', 'repuestos', 'Repuestos', 'general', null, '', false, 100, 'repuesto'),
  ('neumaticos', 'vehiculos', 'neumaticos', 'Neumáticos', 'general', null, '', false, 100, 'neumatico cubierta'),
  ('llantas', 'vehiculos', 'llantas', 'Llantas', 'general', null, '', false, 100, 'llanta'),
  ('accesorios-autos', 'vehiculos', 'accesorios-autos', 'Accesorios para autos', 'general', null, '', false, 100, 'accesorio auto'),
  ('accesorios-motos', 'vehiculos', 'accesorios-motos', 'Accesorios para motos', 'general', null, '', false, 100, 'accesorio moto'),
  ('audio-vehiculos', 'vehiculos', 'audio-vehiculos', 'Audio para vehículos', 'general', null, '', false, 100, 'estereo'),
  ('lubricantes', 'vehiculos', 'lubricantes', 'Lubricantes', 'general', null, '', false, 100, 'aceite lubricante'),
  ('gnc', 'vehiculos', 'gnc', 'GNC', 'general', null, '', false, 100, 'gnc gas'),
  ('herramientas-vehiculo', 'vehiculos', 'herramientas-vehiculo', 'Herramientas para vehículos', 'general', null, '', false, 100, 'herramienta auto'),
  ('limpieza-vehiculos', 'vehiculos', 'limpieza-vehiculos', 'Limpieza para vehículos', 'general', null, '', false, 100, 'limpieza auto'),
  ('seguridad-vehiculos', 'vehiculos', 'seguridad-vehiculos', 'Seguridad para vehículos', 'general', null, '', false, 100, 'seguridad auto'),
  ('tuning', 'vehiculos', 'tuning', 'Tuning', 'general', null, '', false, 100, 'tuning'),
  ('performance', 'vehiculos', 'performance', 'Performance', 'general', null, '', false, 100, 'performance'),
  ('gps', 'vehiculos', 'gps', 'GPS', 'general', null, '', false, 100, 'gps'),
  ('maquillaje', 'belleza', 'maquillaje', 'Maquillaje', 'general', null, '', false, 100, 'maquillaje'),
  ('perfumes', 'belleza', 'perfumes', 'Perfumes', 'general', null, '', false, 100, 'perfume fragancia'),
  ('cosmetica', 'belleza', 'cosmetica', 'Cosmética', 'general', null, '', false, 100, 'cosmetica'),
  ('cuidado-facial', 'belleza', 'cuidado-facial', 'Cuidado facial', 'general', null, '', false, 100, 'facial crema'),
  ('cuidado-corporal', 'belleza', 'cuidado-corporal', 'Cuidado corporal', 'general', null, '', false, 100, 'corporal'),
  ('cuidado-cabello', 'belleza', 'cuidado-cabello', 'Cuidado del cabello', 'general', null, '', false, 100, 'shampoo cabello'),
  ('peluqueria', 'belleza', 'peluqueria', 'Productos para peluquería', 'general', null, '', false, 100, 'peluqueria'),
  ('barberia', 'belleza', 'barberia', 'Barbería', 'general', null, '', false, 100, 'barberia'),
  ('manicura', 'belleza', 'manicura', 'Manicura', 'general', null, '', false, 100, 'unas manicura'),
  ('pedicura', 'belleza', 'pedicura', 'Pedicura', 'general', null, '', false, 100, 'pedicura'),
  ('depilacion', 'belleza', 'depilacion', 'Depilación', 'general', null, '', false, 100, 'depilacion'),
  ('higiene-personal', 'belleza', 'higiene-personal', 'Higiene personal', 'general', null, '', false, 100, 'higiene'),
  ('accesorios-belleza', 'belleza', 'accesorios-belleza', 'Accesorios de belleza', 'general', null, '', false, 100, 'accesorio belleza'),
  ('secadores', 'belleza', 'secadores', 'Secadores', 'general', null, '', false, 100, 'secador'),
  ('planchitas', 'belleza', 'planchitas', 'Planchitas', 'general', null, '', false, 100, 'planchita'),
  ('rizadores', 'belleza', 'rizadores', 'Rizadores', 'general', null, '', false, 100, 'rizador'),
  ('maquinas-afeitar', 'belleza', 'maquinas-afeitar', 'Máquinas de afeitar', 'general', null, '', false, 100, 'afeitadora'),
  ('herramientas-manuales', 'herramientas-construccion', 'herramientas-manuales', 'Herramientas manuales', 'general', null, '', false, 100, 'manual'),
  ('herramientas-electricas', 'herramientas-construccion', 'herramientas-electricas', 'Herramientas eléctricas', 'general', null, '', false, 100, 'electrica'),
  ('herramientas-neumaticas', 'herramientas-construccion', 'herramientas-neumaticas', 'Herramientas neumáticas', 'general', null, '', false, 100, 'neumatica'),
  ('herramientas-industriales', 'herramientas-construccion', 'herramientas-industriales', 'Herramientas industriales', 'general', null, '', false, 100, 'industrial'),
  ('herramientas-jardin', 'herramientas-construccion', 'herramientas-jardin', 'Herramientas de jardín', 'general', null, '', false, 100, 'jardin'),
  ('taladros', 'herramientas-construccion', 'taladros', 'Taladros', 'general', null, '', false, 100, 'taladro'),
  ('amoladoras', 'herramientas-construccion', 'amoladoras', 'Amoladoras', 'general', null, '', false, 100, 'amoladora'),
  ('soldadoras', 'herramientas-construccion', 'soldadoras', 'Soldadoras', 'general', null, '', false, 100, 'soldadora'),
  ('medicion', 'herramientas-construccion', 'medicion', 'Medición', 'general', null, '', false, 100, 'medicion metro'),
  ('cajas-herramientas', 'herramientas-construccion', 'cajas-herramientas', 'Cajas de herramientas', 'general', null, '', false, 100, 'caja'),
  ('materiales-construccion', 'herramientas-construccion', 'materiales-construccion', 'Materiales de construcción', 'general', null, '', false, 100, 'material construccion'),
  ('electricidad', 'herramientas-construccion', 'electricidad', 'Electricidad', 'general', null, '', false, 100, 'electricidad cable'),
  ('plomeria', 'herramientas-construccion', 'plomeria', 'Plomería', 'general', null, '', false, 100, 'plomeria cano'),
  ('pintura', 'herramientas-construccion', 'pintura', 'Pintura', 'general', null, '', false, 100, 'pintura'),
  ('sanitarios-obra', 'herramientas-construccion', 'sanitarios-obra', 'Sanitarios', 'general', null, '', false, 100, 'sanitario bano'),
  ('pisos', 'herramientas-construccion', 'pisos', 'Pisos', 'general', null, '', false, 100, 'piso'),
  ('revestimientos', 'herramientas-construccion', 'revestimientos', 'Revestimientos', 'general', null, '', false, 100, 'revestimiento'),
  ('aberturas', 'herramientas-construccion', 'aberturas', 'Aberturas', 'general', null, '', false, 100, 'abertura puerta ventana'),
  ('maquinaria', 'herramientas-construccion', 'maquinaria', 'Maquinaria', 'general', null, '', false, 100, 'maquinaria'),
  ('seguridad-obra', 'herramientas-construccion', 'seguridad-obra', 'Elementos de seguridad', 'general', null, '', false, 100, 'casco seguridad'),
  ('obras', 'herramientas-construccion', 'obras', 'Construcción', 'general', null, '', false, 100, 'construccion obra'),
  ('juguetes', 'juguetes-bebes', 'juguetes', 'Juguetes', 'general', null, '', false, 100, 'juguete'),
  ('juegos-mesa', 'juguetes-bebes', 'juegos-mesa', 'Juegos de mesa', 'general', null, '', false, 100, 'juego mesa'),
  ('juegos-cartas', 'juguetes-bebes', 'juegos-cartas', 'Juegos de cartas', 'general', null, '', false, 100, 'cartas'),
  ('munecos', 'juguetes-bebes', 'munecos', 'Muñecos', 'general', null, '', false, 100, 'muneco'),
  ('munecas', 'juguetes-bebes', 'munecas', 'Muñecas', 'general', null, '', false, 100, 'muneca'),
  ('peluches', 'juguetes-bebes', 'peluches', 'Peluches', 'general', null, '', false, 100, 'peluche'),
  ('figuras', 'juguetes-bebes', 'figuras', 'Figuras', 'general', null, '', false, 100, 'figura'),
  ('coleccionables', 'juguetes-bebes', 'coleccionables', 'Coleccionables', 'general', null, '', false, 100, 'coleccionable'),
  ('juegos-construccion', 'juguetes-bebes', 'juegos-construccion', 'Juegos de construcción', 'general', null, '', false, 100, 'bloques'),
  ('bloques-encastre', 'juguetes-bebes', 'bloques-encastre', 'Bloques de encastre', 'general', null, '', false, 100, 'lego encastre'),
  ('juguetes-electronicos', 'juguetes-bebes', 'juguetes-electronicos', 'Juguetes electrónicos', 'general', null, '', false, 100, 'juguete electronico'),
  ('juegos-exterior', 'juguetes-bebes', 'juegos-exterior', 'Juegos de exterior', 'general', null, '', false, 100, 'exterior infantil'),
  ('disfraces', 'juguetes-bebes', 'disfraces', 'Disfraces', 'general', null, '', false, 100, 'disfraz'),
  ('ropa-bebe', 'juguetes-bebes', 'ropa-bebe', 'Ropa de bebé', 'general', null, '', false, 100, 'bebe'),
  ('ropa-infantil-ninos', 'juguetes-bebes', 'ropa-infantil-ninos', 'Ropa infantil', 'general', null, '', false, 100, 'infantil'),
  ('calzado-infantil', 'juguetes-bebes', 'calzado-infantil', 'Calzado infantil', 'general', null, '', false, 100, 'calzado nino'),
  ('cochecitos', 'juguetes-bebes', 'cochecitos', 'Cochecitos', 'general', null, '', false, 100, 'cochecito'),
  ('sillas-bebe', 'juguetes-bebes', 'sillas-bebe', 'Sillas para bebé', 'general', null, '', false, 100, 'silla bebe'),
  ('seguridad-infantil', 'juguetes-bebes', 'seguridad-infantil', 'Seguridad infantil', 'general', null, '', false, 100, 'seguridad bebe'),
  ('lactancia', 'juguetes-bebes', 'lactancia', 'Productos de lactancia', 'general', null, '', false, 100, 'lactancia'),
  ('higiene-infantil', 'juguetes-bebes', 'higiene-infantil', 'Higiene infantil', 'general', null, '', false, 100, 'panales'),
  ('muebles-bebes', 'juguetes-bebes', 'muebles-bebes', 'Muebles para bebés', 'general', null, '', false, 100, 'cuna'),
  ('perros', 'mascotas', 'perros', 'Perros', 'general', null, '', false, 100, 'perro'),
  ('gatos', 'mascotas', 'gatos', 'Gatos', 'general', null, '', false, 100, 'gato'),
  ('aves', 'mascotas', 'aves', 'Aves', 'general', null, '', false, 100, 'ave pajaro'),
  ('peces', 'mascotas', 'peces', 'Peces', 'general', null, '', false, 100, 'pez acuario'),
  ('reptiles', 'mascotas', 'reptiles', 'Reptiles', 'general', null, '', false, 100, 'reptil'),
  ('roedores', 'mascotas', 'roedores', 'Roedores', 'general', null, '', false, 100, 'roedor hamster'),
  ('caballos', 'mascotas', 'caballos', 'Caballos', 'general', null, '', false, 100, 'caballo'),
  ('alimentos-mascotas', 'mascotas', 'alimentos-mascotas', 'Alimentos para mascotas', 'general', null, '', false, 100, 'alimento balanceado'),
  ('snacks-mascotas', 'mascotas', 'snacks-mascotas', 'Snacks para mascotas', 'general', null, '', false, 100, 'snack mascota'),
  ('collares', 'mascotas', 'collares', 'Collares', 'general', null, '', false, 100, 'collar'),
  ('correas', 'mascotas', 'correas', 'Correas', 'general', null, '', false, 100, 'correa'),
  ('camas-mascotas', 'mascotas', 'camas-mascotas', 'Camas para mascotas', 'general', null, '', false, 100, 'cama mascota'),
  ('casas-mascotas', 'mascotas', 'casas-mascotas', 'Casas para mascotas', 'general', null, '', false, 100, 'casa mascota'),
  ('juguetes-mascotas', 'mascotas', 'juguetes-mascotas', 'Juguetes para mascotas', 'general', null, '', false, 100, 'juguete mascota'),
  ('higiene-mascotas', 'mascotas', 'higiene-mascotas', 'Higiene para mascotas', 'general', null, '', false, 100, 'higiene mascota'),
  ('accesorios-mascotas', 'mascotas', 'accesorios-mascotas', 'Accesorios para mascotas', 'general', null, '', false, 100, 'accesorio mascota'),
  ('ropa-mascotas', 'mascotas', 'ropa-mascotas', 'Ropa para mascotas', 'general', null, '', false, 100, 'ropa mascota'),
  ('transporte-mascotas', 'mascotas', 'transporte-mascotas', 'Transporte para mascotas', 'general', null, '', false, 100, 'transportadora'),
  ('cuidado-mascotas', 'mascotas', 'cuidado-mascotas', 'Cuidado de mascotas', 'general', null, '', false, 100, 'cuidado veterinario'),
  ('casas', 'inmuebles', 'casas', 'Casas', 'general', null, '', false, 100, 'casa'),
  ('departamentos', 'inmuebles', 'departamentos', 'Departamentos', 'general', null, '', false, 100, 'departamento depto'),
  ('terrenos', 'inmuebles', 'terrenos', 'Terrenos', 'general', null, '', false, 100, 'terreno'),
  ('lotes', 'inmuebles', 'lotes', 'Lotes', 'general', null, '', false, 100, 'lote'),
  ('locales', 'inmuebles', 'locales', 'Locales', 'general', null, '', false, 100, 'local'),
  ('oficinas', 'inmuebles', 'oficinas', 'Oficinas', 'general', null, '', false, 100, 'oficina'),
  ('campos', 'inmuebles', 'campos', 'Campos', 'general', null, '', false, 100, 'campo'),
  ('cocheras', 'inmuebles', 'cocheras', 'Cocheras', 'general', null, '', false, 100, 'cochera'),
  ('galpones', 'inmuebles', 'galpones', 'Galpones', 'general', null, '', false, 100, 'galpon'),
  ('depositos', 'inmuebles', 'depositos', 'Depósitos', 'general', null, '', false, 100, 'deposito'),
  ('consultorios', 'inmuebles', 'consultorios', 'Consultorios', 'general', null, '', false, 100, 'consultorio'),
  ('ph', 'inmuebles', 'ph', 'PH', 'general', null, '', false, 100, 'ph'),
  ('quintas', 'inmuebles', 'quintas', 'Quintas', 'general', null, '', false, 100, 'quinta'),
  ('fondos-comercio', 'inmuebles', 'fondos-comercio', 'Fondos de comercio', 'general', null, '', false, 100, 'fondo comercio'),
  ('equipamiento-industrial', 'industrias-oficinas', 'equipamiento-industrial', 'Equipamiento industrial', 'general', null, '', false, 100, 'industrial'),
  ('equipamiento-comercial', 'industrias-oficinas', 'equipamiento-comercial', 'Equipamiento comercial', 'general', null, '', false, 100, 'comercial'),
  ('equipamiento-oficinas', 'industrias-oficinas', 'equipamiento-oficinas', 'Equipamiento para oficinas', 'general', null, '', false, 100, 'oficina'),
  ('equipamiento-medico', 'industrias-oficinas', 'equipamiento-medico', 'Equipamiento médico', 'general', null, '', false, 100, 'medico'),
  ('arquitectura', 'industrias-oficinas', 'arquitectura', 'Arquitectura', 'general', null, '', false, 100, 'arquitectura'),
  ('diseno', 'industrias-oficinas', 'diseno', 'Diseño', 'general', null, '', false, 100, 'diseno'),
  ('embalaje', 'industrias-oficinas', 'embalaje', 'Embalaje', 'general', null, '', false, 100, 'embalaje packaging'),
  ('logistica', 'industrias-oficinas', 'logistica', 'Logística', 'general', null, '', false, 100, 'logistica'),
  ('grafica', 'industrias-oficinas', 'grafica', 'Gráfica', 'general', null, '', false, 100, 'grafica'),
  ('impresion', 'industrias-oficinas', 'impresion', 'Impresión', 'general', null, '', false, 100, 'impresion'),
  ('publicidad', 'industrias-oficinas', 'publicidad', 'Publicidad', 'general', null, '', false, 100, 'publicidad'),
  ('seguridad-laboral', 'industrias-oficinas', 'seguridad-laboral', 'Seguridad laboral', 'general', null, '', false, 100, 'seguridad laboral'),
  ('gastronomia', 'industrias-oficinas', 'gastronomia', 'Gastronomía', 'general', null, '', false, 100, 'gastronomia'),
  ('hoteleria', 'industrias-oficinas', 'hoteleria', 'Hotelería', 'general', null, '', false, 100, 'hoteleria'),
  ('insumos-comerciales', 'industrias-oficinas', 'insumos-comerciales', 'Insumos comerciales', 'general', null, '', false, 100, 'insumo'),
  ('agricultura', 'agro', 'agricultura', 'Agricultura', 'general', null, '', false, 100, 'agricultura'),
  ('semillas', 'agro', 'semillas', 'Semillas', 'general', null, '', false, 100, 'semilla'),
  ('fertilizantes', 'agro', 'fertilizantes', 'Fertilizantes', 'general', null, '', false, 100, 'fertilizante'),
  ('maquinaria-agricola', 'agro', 'maquinaria-agricola', 'Maquinaria agrícola', 'general', null, '', false, 100, 'tractor'),
  ('riego', 'agro', 'riego', 'Riego', 'general', null, '', false, 100, 'riego'),
  ('ganaderia', 'agro', 'ganaderia', 'Ganadería', 'general', null, '', false, 100, 'ganaderia'),
  ('apicultura', 'agro', 'apicultura', 'Apicultura', 'general', null, '', false, 100, 'apicultura miel'),
  ('herramientas-agro', 'agro', 'herramientas-agro', 'Herramientas agropecuarias', 'general', null, '', false, 100, 'herramienta agro'),
  ('insumos-agro', 'agro', 'insumos-agro', 'Insumos agropecuarios', 'general', null, '', false, 100, 'insumo agro'),
  ('proteccion-cultivos', 'agro', 'proteccion-cultivos', 'Protección de cultivos', 'general', null, '', false, 100, 'cultivo'),
  ('energia-renovable', 'agro', 'energia-renovable', 'Energía renovable', 'general', null, '', false, 100, 'solar renovable'),
  ('equipamiento-medico-salud', 'salud-medica', 'equipamiento-medico-salud', 'Equipamiento médico', 'general', null, '', false, 100, 'equipo medico'),
  ('ortopedia', 'salud-medica', 'ortopedia', 'Ortopedia', 'general', null, '', false, 100, 'ortopedia'),
  ('movilidad', 'salud-medica', 'movilidad', 'Movilidad', 'general', null, '', false, 100, 'silla ruedas'),
  ('cuidado-salud', 'salud-medica', 'cuidado-salud', 'Cuidado de la salud', 'general', null, '', false, 100, 'salud'),
  ('masajes', 'salud-medica', 'masajes', 'Masajes', 'general', null, '', false, 100, 'masaje'),
  ('insumos-medicos', 'salud-medica', 'insumos-medicos', 'Insumos médicos', 'general', null, '', false, 100, 'insumo medico'),
  ('rehabilitacion', 'salud-medica', 'rehabilitacion', 'Productos de rehabilitación', 'general', null, '', false, 100, 'rehabilitacion'),
  ('guitarras', 'instrumentos-musicales', 'guitarras', 'Guitarras', 'general', null, '', false, 100, 'guitarra'),
  ('bajos', 'instrumentos-musicales', 'bajos', 'Bajos', 'general', null, '', false, 100, 'bajo'),
  ('teclados', 'instrumentos-musicales', 'teclados', 'Teclados', 'general', null, '', false, 100, 'teclado'),
  ('pianos', 'instrumentos-musicales', 'pianos', 'Pianos', 'general', null, '', false, 100, 'piano'),
  ('baterias', 'instrumentos-musicales', 'baterias', 'Baterías', 'general', null, '', false, 100, 'bateria'),
  ('percusion', 'instrumentos-musicales', 'percusion', 'Percusión', 'general', null, '', false, 100, 'percusion'),
  ('vientos', 'instrumentos-musicales', 'vientos', 'Instrumentos de viento', 'general', null, '', false, 100, 'viento saxo'),
  ('microfonos', 'instrumentos-musicales', 'microfonos', 'Micrófonos', 'general', null, '', false, 100, 'microfono'),
  ('amplificadores', 'instrumentos-musicales', 'amplificadores', 'Amplificadores', 'general', null, '', false, 100, 'amplificador'),
  ('equipos-dj', 'instrumentos-musicales', 'equipos-dj', 'Equipos DJ', 'general', null, '', false, 100, 'dj'),
  ('estudio-musical', 'instrumentos-musicales', 'estudio-musical', 'Equipamiento de estudio', 'general', null, '', false, 100, 'estudio'),
  ('parlantes', 'instrumentos-musicales', 'parlantes', 'Parlantes', 'general', null, '', false, 100, 'parlante'),
  ('libros', 'libros-arte', 'libros', 'Libros', 'general', null, '', false, 100, 'libro'),
  ('revistas', 'libros-arte', 'revistas', 'Revistas', 'general', null, '', false, 100, 'revista'),
  ('comics', 'libros-arte', 'comics', 'Cómics', 'general', null, '', false, 100, 'comic historieta'),
  ('libreria', 'libros-arte', 'libreria', 'Librería', 'general', null, '', false, 100, 'libreria'),
  ('material-escolar', 'libros-arte', 'material-escolar', 'Material escolar', 'general', null, '', false, 100, 'escolar'),
  ('material-artistico', 'libros-arte', 'material-artistico', 'Material artístico', 'general', null, '', false, 100, 'artistico'),
  ('pintura-artistica', 'libros-arte', 'pintura-artistica', 'Pintura artística', 'general', null, '', false, 100, 'oleo acrilico'),
  ('dibujo', 'libros-arte', 'dibujo', 'Dibujo', 'general', null, '', false, 100, 'dibujo'),
  ('manualidades', 'libros-arte', 'manualidades', 'Manualidades', 'general', null, '', false, 100, 'manualidad'),
  ('merceria', 'libros-arte', 'merceria', 'Mercería', 'general', null, '', false, 100, 'merceria'),
  ('arte', 'libros-arte', 'arte', 'Arte', 'general', null, '', false, 100, 'arte'),
  ('joyas', 'joyas-relojes', 'joyas', 'Joyas', 'general', null, '', false, 100, 'joya'),
  ('bijouterie', 'joyas-relojes', 'bijouterie', 'Bijouterie', 'general', null, '', false, 100, 'bijouterie'),
  ('relojes', 'joyas-relojes', 'relojes', 'Relojes', 'general', null, '', false, 100, 'reloj'),
  ('piercings', 'joyas-relojes', 'piercings', 'Piercings', 'general', null, '', false, 100, 'piercing'),
  ('piedras', 'joyas-relojes', 'piedras', 'Piedras preciosas', 'general', null, '', false, 100, 'piedra'),
  ('insumos-joyeria', 'joyas-relojes', 'insumos-joyeria', 'Insumos para joyería', 'general', null, '', false, 100, 'joyeria'),
  ('joyeros', 'joyas-relojes', 'joyeros', 'Joyeros', 'general', null, '', false, 100, 'joyero'),
  ('accesorios-joyas', 'joyas-relojes', 'accesorios-joyas', 'Accesorios', 'general', null, '', false, 100, 'accesorio joya'),
  ('antiguedades-objetos', 'antiguedades', 'antiguedades-objetos', 'Antigüedades', 'general', null, '', false, 100, 'antiguedad'),
  ('monedas', 'antiguedades', 'monedas', 'Monedas', 'general', null, '', false, 100, 'moneda numismatica'),
  ('billetes', 'antiguedades', 'billetes', 'Billetes', 'general', null, '', false, 100, 'billete'),
  ('filatelia', 'antiguedades', 'filatelia', 'Filatelia', 'general', null, '', false, 100, 'estampilla'),
  ('coleccionables-varios', 'antiguedades', 'coleccionables-varios', 'Coleccionables', 'general', null, '', false, 100, 'coleccionable'),
  ('figuras-coleccion', 'antiguedades', 'figuras-coleccion', 'Figuras de colección', 'general', null, '', false, 100, 'figura'),
  ('posters', 'antiguedades', 'posters', 'Pósters', 'general', null, '', false, 100, 'poster afiche'),
  ('banderas', 'antiguedades', 'banderas', 'Banderas', 'general', null, '', false, 100, 'bandera'),
  ('objetos-historicos', 'antiguedades', 'objetos-historicos', 'Objetos históricos', 'general', null, '', false, 100, 'historico'),
  ('coleccionables-deportivos', 'antiguedades', 'coleccionables-deportivos', 'Coleccionables deportivos', 'general', null, '', false, 100, 'deporte coleccion'),
  ('cotillon', 'fiestas-eventos', 'cotillon', 'Cotillón', 'general', null, '', false, 100, 'cotillon'),
  ('decoracion-fiestas', 'fiestas-eventos', 'decoracion-fiestas', 'Decoración para fiestas', 'general', null, '', false, 100, 'decoracion fiesta'),
  ('disfraces-fiesta', 'fiestas-eventos', 'disfraces-fiesta', 'Disfraces para fiestas', 'general', null, '', false, 100, 'disfraz'),
  ('souvenirs', 'fiestas-eventos', 'souvenirs', 'Souvenirs', 'general', null, '', false, 100, 'souvenir'),
  ('invitaciones', 'fiestas-eventos', 'invitaciones', 'Invitaciones', 'general', null, '', false, 100, 'invitacion'),
  ('globos', 'fiestas-eventos', 'globos', 'Globos', 'general', null, '', false, 100, 'globo'),
  ('confeti', 'fiestas-eventos', 'confeti', 'Confeti', 'general', null, '', false, 100, 'confeti'),
  ('articulos-fiestas', 'fiestas-eventos', 'articulos-fiestas', 'Artículos para fiestas', 'general', null, '', false, 100, 'fiesta'),
  ('decoracion-eventos', 'fiestas-eventos', 'decoracion-eventos', 'Decoración para eventos', 'general', null, '', false, 100, 'evento'),
  ('servicio-diseno', 'servicios', 'servicio-diseno', 'Diseño', 'general', null, '', false, 100, 'diseno'),
  ('fotografia', 'servicios', 'fotografia', 'Fotografía', 'general', null, '', false, 100, 'fotografia foto'),
  ('marketing', 'servicios', 'marketing', 'Marketing', 'general', null, '', false, 100, 'marketing'),
  ('community-manager', 'servicios', 'community-manager', 'Community manager', 'general', null, '', false, 100, 'community redes'),
  ('programacion', 'servicios', 'programacion', 'Programación', 'general', null, '', false, 100, 'programacion software'),
  ('cursos', 'servicios', 'cursos', 'Cursos', 'general', null, '', false, 100, 'curso'),
  ('clases', 'servicios', 'clases', 'Clases particulares', 'general', null, '', false, 100, 'clase particular'),
  ('transporte', 'servicios', 'transporte', 'Transporte', 'general', null, '', false, 100, 'transporte'),
  ('delivery', 'servicios', 'delivery', 'Delivery', 'general', null, '', false, 100, 'delivery envio'),
  ('turismo', 'servicios', 'turismo', 'Turismo', 'general', null, '', false, 100, 'turismo'),
  ('servicio-belleza', 'servicios', 'servicio-belleza', 'Belleza', 'general', null, '', false, 100, 'belleza'),
  ('servicios-mascotas', 'servicios', 'servicios-mascotas', 'Servicios para mascotas', 'general', null, '', false, 100, 'mascota'),
  ('servicios-oficinas', 'servicios', 'servicios-oficinas', 'Servicios para oficinas', 'general', null, '', false, 100, 'oficina'),
  ('servicio-tecnologia', 'servicios', 'servicio-tecnologia', 'Tecnología', 'general', null, '', false, 100, 'tecnologia'),
  ('imprenta', 'servicios', 'imprenta', 'Imprenta', 'general', null, '', false, 100, 'imprenta'),
  ('reparaciones', 'servicios', 'reparaciones', 'Reparaciones', 'general', null, '', false, 100, 'reparacion'),
  ('mantenimiento', 'servicios', 'mantenimiento', 'Mantenimiento', 'general', null, '', false, 100, 'mantenimiento'),
  ('servicio-construccion', 'servicios', 'servicio-construccion', 'Construcción', 'general', null, '', false, 100, 'construccion'),
  ('asesoramiento', 'servicios', 'asesoramiento', 'Asesoramiento profesional', 'general', null, '', false, 100, 'asesoramiento')
on conflict (id) do nothing;
